/** This Node.js file represents the server side (with Express framework) for form data 
 * 
 *  Author: Cole Turner
 */ 

// start the Express framework and make it accessible via the reference
const express = require("express");

// define the top level Express function
const server = express();

// set the port where the server listens for clients
const port = 3078;

// enable the server to recognize JSON format
server.use(express.json());

// enable incoming "name":"value" pairs to be any type including arrays
server.use(express.urlencoded({ extended: true }));

/*
  The purpose of this function is to execute the instructions
  necessary: to allow a request from any origin to access this site's content;
  allow only GET and POST requests; and to only accept requests that include
  "Content-Type".

  @param req - request object generated by the HTTP event
  @param res - response object generated by the HTTP event
  @param next - predefined function used when request/response cycle is not terminated
*/
const allowCrossDomain = function (req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Methods", "GET,POST");
  res.header("Access-Control-Allow-Headers", "Content-Type");
  next();
};

// set domain characteristics defined above
server.use(allowCrossDomain);

/** This function responds to a post request. 
 * 
 */
server.post ({

});

/** This function responds to a get request.
 * 
 */
server.get({

});

/** This function prints a message to the Node.js console when the server is listening for clients.
 * 
 */
server.listen(port, function () {
  console.log("Listening on port 3078");
});



